[versions]


junitJupiter = "5.7.0"
node = "18.12.1"
defaultTs = "3.9.5"
defaultNpmPackage = "0.5.8-rc.5"
kotlinSerialization = "1.0.0-RC"
antlr4 = "4.7.1"
protobufGradlePlugin = "0.8.13"
protobufImplementation = "3.20.1"
